//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropDown_wise_fill_GridData.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTeam
    {
        public int Employee_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Manager_ID { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsManager { get; set; }
    }
}
